name: Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ddnet-rs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: ./.ci/build_individually.sh

